### ISSUE TITLE
Mining Rewards not being processed at all now.. 

### ISSUE THREAD

**Issue by RayT69** [PoWx-Org/obtc-core#18]
mining rewards are not being paid since yesterday..  block number 45887 is stuck on 92/100 for half a day (approximately)..
There are (more than) 15 pending payments plus the new ones i cannot see yet.. 
Maybe server reboot required etc??

**Comment by RayT69** [comment]
a day later.. the mining pool now has 46 workers - double when i started.. and still the confirmations for my payments are not being processed.. i have had only a small amount reach my wallet since yesterday. all other payments (now there are 15 with more to follow - maybe another 50? ) please look at why the payments are taking so long to complete confirmations (more than 24 hours)..

**Comment by RayT69** [comment]
Good to see this is an echo chamber..  i like talking to myself anyway .. :)   In case someone reads this.. The pending payments have caught up until about 2 days ago. Now i have NO pending payments from the past few days even though i have been mining for a couple of hours..  this is stopping me from mining any further..

**Comment by hidaloop** [comment]
Hello @RayT69! My apologies for a huge response time. If you are still here could I kindly ask you to move to a different thread, as your question is not really related to this project. 
Please follow the [link](https://github.com/PoWx-Org/obtc-pool-web-ui/issues/2)
Thanks.
