### ISSUE TITLE
Export Private Keys

### ISSUE THREAD

**Issue by raspy313** [PoWx-Org/obtc-core#6]
I want to export the private keys into a readable format to use in oBTC blue wallet.
Can private keys, or a QR code generator be implemented ?

Or 

Is there a way to view the wallet data as a mnemonic phrase for use in other wallets ?

**Comment by username1565** [comment]
@raspy313 , to get PrivateKey from OBTC-address, need to follow the following steps, in OBTC-wallet:
1. Generate OBTC-address: Receive -> Create new receiving address.
2. Copy generated addres -> Just copy this.
3. Go to console: Window -> Console.
4. Dump private key of this address -> Type `dumpprivkey OBTC_ADDRESS` -> Privkey on output.
5. Save privkey.
6. Import privkey if need: `Window -> Console` -> `importprivkey YOUR_SAVED_PRIVATE_KEY`.
