### ISSUE TITLE
Error when running ./bitcoind

### ISSUE THREAD

**Issue by SNatural** [PoWx-Org/obtc-core#8]
I got this error when running ./bitcoind
bitcoind: chainparams.cpp:104: CMainParams::CMainParams(): Assertion `consensus.hashGenesisBlock == GENESIS_HASH' failed. Aborted (core dumped)

How can I fix it?

**Comment by masterdezign** [comment]
This is not normal actually. Can you print out `consensus.hashGenesisBlock`? If it's not equivalent to `uint256S("0000000000115c7a7e3ff65d77ee96de527953ca6e43e77246929741408f95c0")`, there is something wrong with your compiler or with your code.

**Comment by pkvk** [comment]
This is not normal actually. Can you print out consensus.hashGenesisBlock? If it's not equivalent to uint256S("0000000000115c7a7e3ff65d77ee96de527953ca6e43e77246929741408f95c0"), there is something wrong with your compiler or with your code.

**Comment by SNatural** [comment]
The issue has been resolved.

**Comment by kr1z1s** [comment]
> The issue has been resolved.

How was it fixed? I have same error.

**Comment by SNatural** [comment]
@kr1z1s 
Clone other branches instead of master.

**Comment by kr1z1s** [comment]
> @kr1z1s Clone other branches instead of master.

I resolved. Need compile with gcc 7

**Comment by SNatural** [comment]
@kr1z1s 
You are right, the issue has gone when compiling with gcc 7.
